[package]
name = "arithmetic-coding"
version = "0.3.0"
edition = "2021"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bincode = "1.3.3"
debug_print = "1.0.0"
serde = { version = "1.0.196", features = ["serde_derive"] }
